### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by sulvrix** [LukaSimovic/Cryptographic-symmetric-key-algorithms-C-Sharp#1]
Hello Mr. Luka, I was wondering if there was an English version for this project.
The project is amazing and very helpful but it's difficult to translate all variables and functions manually.
Other than that, the message boxes and the tools' names are easy to translate.
If there's not, would you at least translate the variables and functions?
Thank You.

**Comment by LukaSimovic** [comment]
Thank you for your interest. Unfortunately, there is no English version of this project as it was developed during my college days when I didn't yet have the habit of writing code in English.

**Comment by sulvrix** [comment]
No Problem I made my own version, thank for your reply.
Caesar , RSA , Autokey , Playfair are all set I am just stuck on the Simplified DES Algorithm I hope I can fix it soon.
